/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'engine' at '16-7-15 下午2:20' with Gradle 2.7
 *
 * @author engine, @date 16-7-15 下午2:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
